# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Melly' do
use_modular_headers!
use_frameworks!

#Login API
pod 'GoogleSignIn'
pod 'naveridlogin-sdk-ios'
pod 'KakaoSDKCommon'
pod 'KakaoSDKAuth'
pod 'KakaoSDKUser'
pod 'RxKakaoSDKCommon'
pod 'RxKakaoSDKAuth'
pod 'RxKakaoSDKUser'

#Server API
pod 'Alamofire'
pod 'RxAlamofire'
pod 'Kingfisher'

#UI framework
pod 'SnapKit', '~> 5.0.0'
pod 'Then'
pod 'RxSwift'
pod 'RxCocoa'
pod 'NMapsMap'
pod 'FloatingPanel'
pod 'DropDown'

#Firebase
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'FirebaseAnalytics'
end
